# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7721cc0d529e2347f588d2029ae031cc"
name = "sep7"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-10"



[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes  = "write_products,read_products ,read_discounts,write_discounts,read_metaobjects, write_metaobjects,write_metaobject_definitions,read_metaobject_definitions"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

